### ISSUE TITLE
Issue to Run code

### ISSUE THREAD

**Issue by Debmani** [PepeOfMath/TrapezoidalMap#1]
When I am trying to run PointSearch.java it is only printing the instructions.How Do I run the PointSearch.java using a file path argument??
![Capture](https://user-images.githubusercontent.com/49718523/56345620-c7d80300-61dd-11e9-89bc-004277be50d5.JPG)

**Comment by TylerChenhall** [comment]
Here are a few links on providing Java arguments in IntelliJ IDEA:

https://users.drew.edu/bburd/JavaForDummies6/CommandLineIntelliJIDEA.pdf

https://stackoverflow.com/questions/2066307/how-do-you-input-commandline-argument-in-intellij-idea

**Comment by Debmani** [comment]
Thank you very much TylerChenhall for your prompt response.I am very new to computational geometry and facing several silly issues.

kindly help once more please!

I have checked your suggested links and then tried to run PointSearch.java by command line arguments but showing error below :


![Error2](https://user-images.githubusercontent.com/49718523/56498190-45717b00-651e-11e9-9008-0554e6aa8fe8.JPG)
![Error3](https://user-images.githubusercontent.com/49718523/56498191-460a1180-651e-11e9-8eb1-1ee01845cc9f.JPG)

I am trying to create a trapezoidal map from a svg file.If you will help me I shall be highly obliged.
kindly share your email id so that I can contact you for further support.

You can contact me via : debmanisaha1994@gmail.com

**Comment by TylerChenhall** [comment]
The current implementation only supports a plaintext file format. You can get an idea for the format by either

* Running the app once using the graphical segment creator, which will save your segments to a file with correct format

or 

* Reading the code for getLines and storeLines in PointSearch.java

**Comment by Debmani** [comment]
Hi Tyler,

Thank you for your response.

As pointsearch.java contains main so I have to run that via command line
arguments.

Now my question is that to create a trapezoidal map by inserting segments
drawn by mouse clicks, what format I have to choose in the text file.


I shall be highly obliged if you kindly send me a testcase text file so
that I can try to run by that.

Thank you in anticipation,
Debmani
